// <auto-generated />
namespace WorkoutContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class adding_exercise_objects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_exercise_objects));
        
        string IMigrationMetadata.Id
        {
            get { return "201311080148552_adding_exercise_objects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
